export const LOAD_ROUTES_INITIATION = 'LOAD_ROUTES_INITIATION';
export const LOAD_ROUTES_SUCCESS = 'LOAD_ROUTES_SUCCESS';
export const SELECT_ROUTE = 'SELECT_ROUTE';
export const LOAD_ROUTES_ERROR = 'LOAD_ROUTES_ERROR';
export const CLEAR_ROUTES_ERRORS = 'CLEAR_ROUTES_ERRORS';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';
