export const SCHEDULE_LOAD_INITIATION = 'SCHEDULE_LOAD_INITIATION';
export const SCHEDULE_LOAD_FAILURE = 'SCHEDULE_LOAD_FAILURE';
export const SCHEDULE_LOAD_SUCCESS = 'SCHEDULE_LOAD_SUCCESS';
export const CLEAR_SCHEDULE_ERRORS = 'CLEAR_SCHEDULE_ERRORS';
export const SELECT_SCHEDULE_ITEM = 'SELECT_SCHEDULE_ITEM';
