export const SCHEDULE_LOAD_INITIATION = 'SCHEDULE_LOAD_INITIATION';
export const SCHEDULE_LOAD_FAILURE = 'SCHEDULE_LOAD_FAILURE';
export const SCHEDULE_LOAD_SUCCESS = 'SCHEDULE_LOAD_SUCCESS';
export const CLEAR_SCHEDULE_ERRORS = 'CLEAR_SCHEDULE_ERRORS';
export const SELECT_SCHEDULE_ITEM = 'SELECT_SCHEDULE_ITEM';
export const CLEAR_SELECTED_SCHEDULE_ITEM = 'CLEAR_SELECTED_SCHEDULE_ITEM';
export const TOGGLE_MORE_INFO = 'TOGGLE_MORE_INFO';
