export const LOAD_STATIONS_INITIATION = 'LOAD_STATIONS_INITIATION';
export const LOAD_STATIONS_SUCCESS = 'LOAD_STATIONS_SUCCESS';
export const LOAD_STATIONS_ERROR = 'LOAD_STATIONS_ERROR';
export const SELECT_DEPARTURE_STATION = 'SELECT_DEPARTURE_STATION';
export const SELECT_ARRIVAL_STATION = 'SELECT_ARRIVAL_STATION';
export const SHOW_STATION_ERRORS = 'SHOW_STATION_ERRORS';
export const CLEAR_STATION_ERRORS = 'CLEAR_STATION_ERRORS';
export const CLEAR_SELECTED_STATIONS = 'CLEAR_SELECTED_STATIONS';
