export const LOAD_STATIONS_INITIATION = 'LOAD_STATIONS_INITIATION';
export const LOAD_STATIONS_SUCCESS = 'LOAD_STATIONS_SUCCESS';
export const LOAD_STATIONS_ERROR = 'LOAD_STATIONS_ERROR';
export const SELECT_DEPARTURE_STATION = 'SELECT_DEPARTURE_STATION';
export const SELECT_ARRIVAL_STATION = 'SELECT_ARRIVAL_STATION';
