export const LOAD_STOPS_INITIATION = 'LOAD_STOPS_INITIATION';
export const LOAD_STOPS_SUCCESS = 'LOAD_STOPS_SUCCESS';
export const LOAD_STOPS_ERROR = 'LOAD_STOPS_ERROR';
export const SELECT_DEPARTURE_STOP = 'SELECT_DEPARTURE_STOP';
export const SELECT_ARRIVAL_STOP = 'SELECT_ARRIVAL_STOP';
